
version: 2.1

jobs:
  build:
    working_directory: /var/www/html
    steps:
      - checkout  # Checkout the code from your repository
      - run:
          name: Deploy HTML project
          command: |
            # Copy your HTML project to the remote server using SSH
            scp -r . ubuntu@18.188.85.211:/var/www/html/
          environment:
            SSH_KEY: $SSH_KEY  # Define your SSH key as an environment variable

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Adjust this to your main branch name
