version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: nginx:latest

    steps:
      - checkout

      # Add a step to install scp
      - run:
          name: Install SCP
          command: apt-get update && apt-get install -y openssh-client

      - run:
          name: Deploy to AWS
          command: |
            # Set up SSH key for authentication
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
